export const majors = [
  "Accounting",
  "Aerospace Engineering",
  "Anthropology",
  "Architecture",
  "Art History",
  "Biology",
  "Biomedical Engineering",
  "Business Administration",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Communications",
  "Computer Engineering",
  "Computer Science",
  "Criminal Justice",
  "Economics",
  "Education",
  "Electrical Engineering",
  "English Literature",
  "Environmental Science",
  "Finance",
  "Graphic Design",
  "History",
  "Information Technology",
  "International Relations",
  "Journalism",
  "Marketing",
  "Mathematics",
  "Mechanical Engineering",
  "Music",
  "Nursing",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychology",
  "Public Health",
  "Sociology",
  "Software Engineering",
  "Statistics",
  "Theater Arts"
] as const;
